version: "3.7"
services:
    server:
        build: .
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./src:/app/src
        environment:
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
            - DB_CLIENT=${DB_CLIENT}
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgres
    adminer:
        image: adminer
        ports:
            - 8080:8080
        volumes:
            - adminer:/var/lib/adminer
volumes:
    postgres:
    adminer:
