version: "4.0.1"
services:
    server:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./src:/app/src
        environment:
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8000:80
        environment:
            PMA_ARBITRARY: 1
volumes:
    mysql:
