version: "3.7"
services:
    server:
        build: .
        depends_on:
            - postgres
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./src:/app/src
        environment:
            - PORT=${PORT}
            - NODE_ENV=${NODE_ENV}
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgres
    adminer:
        image: adminer
        depends_on:
            - postgres
        restart: always
        ports:
            - 8080:8080
        volumes:
            - adminer:/var/lib/adminer
volumes:
    postgres:
    adminer:
