version: "4.0.1"
services:
    server:
        build: .
        ports:
            - 5000:5000
        volumes:
            - ./src:/app/src
        environment:
            - NODE_ENV=${NODE_ENV}
    mysql:
        image: mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - 3306:3306
        volumes:
            - ./volumes/mysql:/var/lib/mysql
